# Generated by Django 3.2.13 on 2022-07-25 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
