# Generated by Django 3.2.13 on 2022-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
