# Generated by Django 3.2.13 on 2022-07-27 00:21

from django.db import migrations, models
import signup.validators


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10, validators=[signup.validators.validate_password]),
        ),
    ]
